
version: "3"

services:
  app:
    image: snaksa/spotify-downlader-backend
    build:
      context: .
    container_name: spotify-backend
    volumes:
     - ./src:/var/www/html/src
    ports:
      - "8080:80"
